### ISSUE TITLE
Macrostrat units API errors

### ISSUE THREAD

**Issue by davenquinn** [UW-Macrostrat/macrostrat-api#240]
<img width="446" alt="image" src="https://github.com/user-attachments/assets/22d7135d-608f-45b9-87c2-de4194a1e757">

My column renderer is pretty broken right now for certain columns, and I suspect it can be traced back to some changes to the units API response. Perhaps ordering of results?

Example: https://v2.macrostrat.org/columns/1666

**Comment by davenquinn** [comment]
This is a high-priority one since it breaks user-facing visualizations.

**Comment by davenquinn** [comment]
This is what it should look like:
<img width="546" alt="image" src="https://github.com/user-attachments/assets/00809761-f94b-48e3-9c70-41541982220d">

**Comment by amyfromandi** [comment]
Removed the DISTINCT on units.id which affected the order of units in the response. We need to come up with a different solution to resolve the duplicate units.id issue. We may need to add a GROUP BY clause back in
